# Generated by Django 3.0.3 on 2020-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200224_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
    ]
