# Generated by Django 3.0.3 on 2020-03-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_color_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='list',
            new_name='column',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
