# Generated by Django 3.0.3 on 2020-03-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200302_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=6),
        ),
    ]
